services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DBNAME}
      MYSQL_USER: ${DBUSER}
      MYSQL_PASSWORD: ${DBPASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - main_net

  web:
    build: .
    command: gunicorn act.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media  # <--- ADDED: Syncs Django uploads to the shared volume
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - main_net

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media  # <--- ADDED: Allows Nginx to read the shared uploads
      - ./nginx:/etc/nginx/conf.d
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
      - /root/attandance_desktop/build/web:/var/www/flutter_app
    depends_on:
      - web
    networks:
      - main_net

  certbot:
    image: certbot/certbot
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    networks:
      - main_net

volumes:
  db_data:
  static_volume:
  certbot_conf:
  certbot_www:
  media_volume:  # <--- ADDED: Define the new volume here

networks:
  main_net:
    driver: bridge